source:
  revision: "main"
destination:
  namespace: "demo3"
applications:
  - name: redis
    chart: redis
    values:
      - redis.yaml
  - name: elasticsearch
    chart: elasticsearch
    values:
      - elasticsearch.yaml
