helmDefaults:
  atomic: true
  createNamespace: true
releases:
  - name: argocd-deployment-demo
    chart: ../../charts/argocd-deployment
    namespace: demo
    installed: true
    values:
      - ./values/argocd-deployment.yaml
